import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from dotenv import load_dotenv
from datetime import datetime
import os

load_dotenv()

GMAIL_ADDRESS = os.getenv("GMAIL_ADDRESS")
GMAIL_APP_PASSWORD = os.getenv("GMAIL_APP_PASSWORD")


def send_report(pdf_filepath, recipient_email=None):
    if not recipient_email:
        recipient_email = os.getenv("SCHEDULED_RECIPIENT")

    if not recipient_email:
        print("No recipient email provided. Skipping email.")
        return False

    date_str = datetime.now().strftime("%B %d, %Y")

    msg = MIMEMultipart()
    msg["From"] = GMAIL_ADDRESS
    msg["To"] = recipient_email
    msg["Subject"] = f"Job Market Daily Report — {date_str}"

    body = f"""Hi,

Your daily job market report for {date_str} is attached.

This report was automatically generated by your AI Job Market Agent.
It includes:
- Market overview and sentiment
- Layoffs and hiring freezes
- Companies actively hiring
- In demand skills and roles
- Salary and compensation trends
- Key takeaways for job seekers

Good luck with your search today.

— Your AI Agent"""

    msg.attach(MIMEText(body, "plain"))

    with open(pdf_filepath, "rb") as f:
        attachment = MIMEBase("application", "octet-stream")
        attachment.set_payload(f.read())
        encoders.encode_base64(attachment)
        attachment.add_header(
            "Content-Disposition",
            f"attachment; filename={os.path.basename(pdf_filepath)}"
        )
        msg.attach(attachment)

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
            server.sendmail(GMAIL_ADDRESS, recipient_email, msg.as_string())
        print(f"Report emailed to {recipient_email}")
        return True

    except Exception as e:
        print(f"Could not send email: {e}")
        return False